<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <ImportLombiqHelpfulLibrariesOrchardCore>true</ImportLombiqHelpfulLibrariesOrchardCore>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.props"
          Condition="'$(NuGetBuild)' != 'true' "/>

  <PropertyGroup>
    <Title>Lombiq Helpful Extensions for Orchard Core</Title>
    <Copyright>Copyright © 2013, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Helpful Extensions for Orchard Core: Orchard Core module containing some handy extensions (e.g. useful content types and widgets). It's also available on all sites of DotNest, the Orchard SaaS. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;CodeGeneration;ShapeTracing;Widgets</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Extensions</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Extensions</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Autoroute" Version="2.1.0" />
    <PackageReference Include="OrchardCore.ContentFields" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Contents" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Flows" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Html" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Lists" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Liquid" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Markdown" Version="2.1.0" />
    <PackageReference Include="OrchardCore.MetaWeblog.Abstractions" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Rules.Abstractions" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Workflows" Version="2.1.0" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true' "/>

</Project>
